config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @employee = Employee.new
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.js
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:role, :first_name, :virtual_name, :username_email, :gender, :chat_limit, :email_limit, :is_multisession_allow, :select_volume, :select_ring_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit.html.erb
<div class="modal fade" id="updatemodal" tabindex="-1" role="dialog" aria-labelledby="scrollmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content update-modal">
            <%= render "edit_modal", link: "employee" %> 
        </div>
    </div>
</div>

app/views/employees/_edit_modal.html.erb
<div class="modal-header">
    <h5 class="modal-title" id="scrollmodalLabel">
        Update <%= local_assigns[:link] %>: 
        <%#= @employee.name %> 
    </h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<%= render "form", employee: @employee, operation: "Update" %>

app/views/employees/_employee.html.erb
<tr>
    <td>
        <%= employee.role %>
    </td>
    <td>
        <%= employee.first_name %>
    </td>
    <td>
        <%= employee.virtual_name %>
    </td>
    <td>
        <%= employee.username_email %>
    </td>
    <td>
        <%= employee.gender %>
    </td>
    <td>
        <%= employee.is_multisession_allow=="1" ? "Allowed" : "Disallowed" %>
    </td>
    <td class="operations">
        <%= link_to  edit_employee_path(employee), remote: true  do %>
            <i class="fa fa-edit"></i>
        <% end %>
        &emsp;
        <%= link_to "X", employee, method: :delete, data: { confirm: 'Are you sure?' }, class: " text-danger" %>
    </td>
</tr>

app/views/employees/_form.html.erb
<% gender = ["Male", "Female", "Others"] %>
<% limit = [1,2,3,4,5] %>

<%= form_with(model: employee, local: true) do |form| %>
<%# :html => {:'data-type' => 'json'} %>
    <div class="modal-body">
        <div class="card-body card-block">
            <div class="errors form-group">
              <%= render "form_errors" %>
            </div>
            <div class="form-group">
                <%= form.label :role, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-meh-o"></i></div>
                    <%= form.text_field :role, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. Director</small>
            </div>
            <div class="form-group">
                <%= form.label :first_name, class: "form-control-label" %>
                <i class="fa  fa-asterisk text-danger"></i>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-meh-o"></i></div>
                    <%= form.text_field :first_name, class: "form-control", required: true %>
                </div>
                <small class="form-text text-muted">ex. Joe Moore</small>
            </div>

            <div class="form-group">
                <%= form.label :virtual_first_name, class: "form-control-label" %>
                <i class="fa  fa-asterisk text-danger"></i>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-meh-o"></i></div>
                    <%= form.text_field :virtual_name, class: "form-control", required: true %>
                </div>
                <small class="form-text text-muted">ex. James</small>
            </div>

            <div class="form-group">
                <%= form.label "User Name/Email", class: "form-control-label" %>
                <i class="fa  fa-asterisk text-danger"></i>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-meh-o"></i></div>
                    <%= form.text_field :username_email, class: "form-control", required: true,  :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
                </div>
                <small class="form-text text-muted">ex. example@abc.com</small>
            </div>

            <div class="form-group">
                <%= form.label :gender, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-arrow-circle-o-down"></i></div>
                    <%= form.select :gender, options_for_select(gender, :selected => @employee.gender), { include_blank: true }, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. Male</small>
            </div>

            <div class="form-group">
                <%= form.label :chat_limit, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-arrow-circle-o-down"></i></div>
                    <%= form.select :chat_limit, options_for_select(limit, :selected => @employee.chat_limit), { include_blank: true }, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. 1</small>
            </div>

            <div class="form-group">
                <%= form.label :email_limit, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-arrow-circle-o-down"></i></div>
                    <%= form.select :email_limit, options_for_select(limit, :selected => @employee.email_limit), { include_blank: true }, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. 2</small>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <%= form.label "Multi-Session/Allowed", class: "form-check-label" %> 
                    <%= form.check_box :is_multisession_allow, class: "form-check-input" %>
                </div>
                
            </div>



            <div class="form-group">
                <%= form.label :select_volume, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-arrow-circle-o-down"></i></div>
                    <%= form.select :select_volume, options_for_select(limit, :selected => @employee.select_volume), { include_blank: true }, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. 2</small>
            </div>

            <div class="form-group">
                <%= form.label :select_ring_type, class: "form-control-label" %>
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa  fa-arrow-circle-o-down"></i></div>
                    <%= form.select :select_ring_type, options_for_select(limit, :selected => @employee.select_ring_type), { include_blank: true }, class: "form-control" %>
                </div>
                <small class="form-text text-muted">ex. 2</small>
            </div>

            
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= form.submit local_assigns[:operation], class: "btn btn-primary" %>
    </div>
<% end %>

app/views/employees/_form_errors.html.erb
<% if @employee.errors.any? %>
    <div id="error_explanation ">
        <h5 class='text-danger'><b><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</b></h5>
        <ul>
        <% @employee.errors.full_messages.each do |message| %>
        <li class="text-danger form-control-label"><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/employees/_new.html.erb
<div class="modal fade" id="addmodal" tabindex="-1" role="dialog" aria-labelledby="scrollmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="scrollmodalLabel">Add New employee</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <%= render "form", employee: @employee, operation: "Add" %>
        </div>
    </div>
</div>

app/views/employees/_new_form.html.erb
<% gender = ["Male", "Female", "Others"] %>
<% limit = [1,2,3,4,5] %>

<%= form_with(model: employee, local: true) do |form| %>
    <div class="card-body card-block">
        <div class="errors row form-group">
            <%= render "form_errors" %>
        </div>
        <div class="row form-group">
            <div class="col-12 col-md-4">
                <%= form.text_field :role, class: "form-control", placeholder: "Role" %>
            </div>
            <div class="col-12 col-md-4">
                <%= form.text_field :first_name, class: "form-control", placeholder: "First Name", required: true %>
            </div>
            <div class="col-12 col-md-4">
                <%= form.text_field :virtual_name, class: "form-control", placeholder: "Virtual First Name", required: true %>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-12 col-md-4">
                <%= form.text_field :username_email, class: "form-control", placeholder: "User Name/Email", required: true,  :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
            </div>

            <div class="col-12 col-md-4">
                <%= form.select :gender, options_for_select(gender, :selected => @employee.gender), { prompt: "Gender" }, class: "form-control" %>
            </div>

            <div class="col-12 col-md-4">
                <%= form.select :chat_limit, options_for_select(limit, :selected => @employee.chat_limit), { prompt: "Chat Limit" }, class: "form-control" %>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-12 col-md-4">
                <%= form.select :email_limit, options_for_select(limit, :selected => @employee.email_limit), { prompt: "Email Limit" }, class: "form-control" %>
            </div>
            <div class="col-12 col-md-4">
                <%= form.check_box :is_multisession_allow, class: "form-check-input" %>
                <%= form.label "Multi-Session/Allowed", class: "form-check-label" %> 
            </div>
        </div>

        <div class="row form-group">
            <div class="col-12 col-md-4">
                <%= form.select :select_volume, options_for_select(limit, :selected => @employee.select_volume), { prompt: "Select Volume" }, class: "form-control" %>
            </div>

            <div class="col-12 col-md-4">
                <%= form.select :select_ring_type, options_for_select(limit, :selected => @employee.select_ring_type), { prompt: "Select Ring Type" }, class: "form-control" %>
            </div>
            
        </div>
        <%= form.submit "Save", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        
    </div>
    
    
<% end %>

app/views/employees/create.js.erb
<%# $(".close").click(); %>
$(".errors").html("<%=j render :partial => 'form_errors' %>");	
<%# $(".add-button").click(); %>

app/views/employees/edit.js.erb
$(".update-modal").html("<%=j render :partial => 'edit_modal' %>");	
$(".edit-common-modal").click();

app/views/employees/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag    'employees', media: 'all' %>
<% end %>

<%= render "layouts/left_panel", link: 'employees' %>

<!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <%= render "layouts/header" %>

    <%= render "layouts/table_layout/breadcrumbs", link: ['employees'] %>

    <div class="content mt-3">
        
        <div class="animated">
            

            <div class="row">
                <%= render "layouts/table_layout/notice" %>
                <div class="col-md-12">
                    <div class="card">
                        <%= render "layouts/table_layout/card_header", current_title: "employees" %>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th> Role </th>
                                    <th> First Name </th>
                                    <th> Virtual Name </th>
                                    <th> Username / Email </th>
                                    <th> Gender </th>
                                    <th> Multi Session Allowed </th>
                                    <th> Operations </th>
                                </tr>
                                </thead>
                                <tbody>
                                    <%= render partial: "employee", collection: @employees %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <%= render "new" %>
                    <%= render "edit" %>
                    <span class="edit-common-modal" data-toggle="modal" data-target="#updatemodal"> </span>
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->


</div><!-- /#right-panel -->

<!-- Right Panel -->

<%= javascript_include_tag 'jemployees' %>

app/views/employees/new.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag    'employees', media: 'all' %>
<% end %>

<%= render "layouts/left_panel", link: 'employees' %>

<!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <%= render "layouts/header" %>

    <%= render "layouts/table_layout/breadcrumbs", link: ['employees'] %>

    <div class="content mt-3">
        
        <div class="animated">
            

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <%= render "layouts/table_layout/card_header", current_title: "Add Employee", header_button: "True" %>
                        <%= render "new_form", employee: @employee, operation: "Add" %>
                    </div>
                    
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->


</div><!-- /#right-panel -->

<!-- Right Panel -->

<%= javascript_include_tag 'jemployees' %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @employee.parent %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/update.js.erb
$(".errors").html("<%=j render :partial => 'form_errors' %>");	

app/views/layouts/_header.html.erb
<!-- Header-->
    <header id="header" class="header">

        <div class="header-menu">

            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="header-left">
                    <button class="search-trigger"><i class="fa fa-search"></i></button>
                    <div class="form-inline">
                        <form class="search-form">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                            <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                        </form>
                    </div>

                    <div class="dropdown for-notification">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">5</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                        </div>
                    </div>

                    <div class="dropdown for-message">
                        <button class="btn btn-secondary dropdown-toggle" type="button"
                            id="message"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="ti-email"></i>
                        <span class="count bg-primary">9</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <span class="photo media-left">
                                <%= image_tag "avatar/1.jpg" %>
                                <%# <img alt="avatar" src="avatar/1.jpg"> %>
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                    <p>Hello, this is an example msg</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <span class="photo media-left">
                                <%= image_tag "avatar/2.jpg" %>
                                <%# <img alt="avatar" src="images/avatar/2.jpg" %>
                                </span>
                            <span class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <span class="photo media-left">
                                <%= image_tag "avatar/3.jpg" %>
                                <%# <img alt="avatar" src="images/avatar/3.jpg"> %>
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                    <p>Hello, this is an example msg</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-3" href="#">
                            <span class="photo media-left">
                                <%= image_tag "avatar/4.jpg" %>
                                <%# <img alt="avatar" src="images/avatar/4.jpg"> %>
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </span>
                        </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-5">
                <div class="user-area dropdown float-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= image_tag "admin.jpg", class: "user-avatar rounded-circle" %>
                        <%# <img class="user-avatar rounded-circle" src="images/admin.jpg" alt="User Avatar"> %>
                    </a>

                    <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                            <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                    </div>
                </div>

                <div class="language-select dropdown" id="language-select">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">
                        <i class="flag-icon flag-icon-us"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="language" >
                        <div class="dropdown-item">
                            <span class="flag-icon flag-icon-fr"></span>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-es"></i>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-us"></i>
                        </div>
                        <div class="dropdown-item">
                            <i class="flag-icon flag-icon-it"></i>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </header><!-- /header -->
    <!-- Header-->

app/views/layouts/_left_panel.html.erb
<!-- Left Panel -->

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="./">LOGO NAME</a>
            <a class="navbar-brand hidden" href="./">LOGO</a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!-- /.menu-title -->
                <h3 class="menu-title"> Basics </h3>
                <li class="menu-item-has-children active dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa  fa-circle"></i>Parent - 1</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -1 ", new_employee_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -2 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -3 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -4 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -5 ", employees_url %>
                        </li>
                    </ul>
                </li>

                <li class="menu-item-has-children active dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa  fa-circle"></i>Parent - 1</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -1 ", new_employee_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -2 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -3 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -4 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -5 ", employees_url %>
                        </li>
                    </ul>
                </li>

                <li class="menu-item-has-children active dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa  fa-circle"></i>Parent - 1</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -1 ", new_employee_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -2 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -3 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -4 ", employees_url %>
                        </li>
                        <li>
                            <i class="fa fa-angle-right"></i>
                            <%= link_to "Child -5 ", employees_url %>
                        </li>
                    </ul>
                </li>

                
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
  <head>
    <title>All in One Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag 'apple-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image//x-icon' %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
     <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

      
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <%= javascript_include_tag 'application' %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>    
  </body>
</html>

app/views/layouts/table_layout/_card_header.html.erb
<div class="card-header">
    <span>
        <strong class="card-title"><%= local_assigns[:current_title] %></strong>
    </span>
    <!-- <div class="add-button"> -->
    <% unless local_assigns[:header_button] %>
        <button type="button" class="btn btn-success float-right add-button" data-toggle="modal" data-target="#addmodal">
            <i class="menu-icon fa fa-plus-circle"></i>
        </button>
    <% end %>
    <!-- </div> -->
</div>